# Use root/example user/password credentials
version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-docker-simple
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www/html/
  nginx:
    image: nginx:1.19-alpine
    container_name: php-docker-simple-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      -../src:/var/www
      -./nginx:/etc/nginx/conf.d
